name: Deploy static site

on:
  push:
    branches:
      - test

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: redratinthehat/static-mark:${{ github.sha }}

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Set up K8s context
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host bastion" >> ~/.ssh/config
          echo "  Hostname ${{ vars.BASTION_IP }}" >> ~/.ssh/config
          echo "  User ubuer" >> ~/.ssh/config
          echo "Host 192.168.*" >> ~/.ssh/config
          echo "  ProxyJump bastion" >> ~/.ssh/config
          echo "  User ubuer" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
